index:
    path: /
    controller: ThorWalez\WaybillCreator\Controller\DefaultController::index

create:
    path: /create
    controller: ThorWalez\WaybillCreator\Controller\DefaultController::create

showpdf:
    path: /showpdf
    controller: ThorWalez\WaybillCreator\Controller\DefaultController::viewFile

removepdf:
    path: /removepdf
    controller: ThorWalez\WaybillCreator\Controller\DefaultController::removeFile
